import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/Header";
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import ctheme from './components/theme'
// import "/Users/evercampos/Flash-Card/app/globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          

        <ThemeProvider theme={ctheme}>
          <CssBaseline /> 
          <Header/>
          <main>{children}</main> 
        </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
